default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: ''
  timeout: 5000
  user: postgres

development:
  <<: *default
  database: larpdb_development

test:
  <<: *default
  database: larpdb_test

production:
  <<: *default
  database: larpdb_production
